#!/usr/bin/perl
use strict;
use warnings;
use diagnostics;

##### 
# input : `./latex_corpus/NLP_LATEX_CORPUS/V*`(directory)
# output : `./train_data/V*`(file)
# usage : `./sep_test_data`
#
# process : 
# 	1. filter non-japanese files
# 	2. seprate test and develop data
#####

my @ar_rp_file_corpus = <../latex_corpus/NLP_LATEX_CORPUS/V*/V*>;

#/
# get list of jpn files
# my @ar_rp_file_jpn= grep &get_jpn_files @ar_rp_file_corpus;

# seperate test/dev data
# my (@ar_rp_file_test, @ar_rp_file_dev);
@ar_rp_file_test = grep {
	my num = filename::base() =~ /.../;
	num/4 ? return 1 : push @ar_rp_file_dev, return 0;
} @ar_rp_jpn_file;

&print_log();



sub get_jpn_files {
	
}

sub print_log {
	local $" = "\n";
	my $num_file_corpus = @ar_rp_file_corpus;

	print <<END;
<<< file list in the corpus >>>
@ar_pth_files_corpus

<<< file list in english >>>

<<< file list for development data >>>

<<< file list for test data >>>


number of files in the corpus : $num_file_corpus
number of files in english    : 
numbers for development data  : 
numbers for test data         :
numbers of processed data     :

END
}
