#!/usr/bin/perl
use strict;
use warnings;
use diagnostics;
use utf8;
#binmode(STDOUT, "utf8

opendir $dh, './logs/';
for my $cur_dir (readdir $dh) {
	if ( -d $cur_dir and not '.' and not '..') {
		my $path = './logs/'."$cur_dir".'/tf_idf_weight';
		open $fh, '<:encoding(UTF-8)', $path or die "Cannot open $path : $!";

open 
@tf_idf_ar = 

