#!/usr/bin/perl -w
use strict;

my ($dir_path, @file_list, $total);

foreach (qw/01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22/) {
	$dir_path = "./latex_corpus/NLP_LATEX_CORPUS/V".$_;
	
	@file_list = <$dir_path/*.tex>;
	
	system "cp $dir_path/*.tex ./";
	
	print "V".$_.": ".scalar @file_list." files copied.\n";
	$total += @file_list;

}
print "total: ".$total."\n";
