#!/usr/bin/perl
use strict;

use strict;
use utf8;

use open IO=> ':encoding(utf8)';
binmode STDIN, ':encoding(utf8)';
binmode STDOUT, ':encoding(utf8)';
binmode STDERR, ':encoding(utf8)';

use lib qw(lib);

use Latex2Text ':all';
use CabCommon ':all';


$#ARGV >= 0 || die "Usage: ./Cab [NAME OF LATEX SOURCE FILES]\n";

##### Cab process start
my @latex_files = <@ARGV>;
print scalar @latex_files." input latex files\n";
my $num_done;

{
	for my $path_latex (@latex_files) {
		my $log_dir = get_log_dir($path_latex);

		my $abs_path = File::Spec->catfile($log_dir, "sec_abstract");
		my $int_path = File::Spec->catfile($log_dir, "sec_intro");

		my @all_abs = read_all_line($abs_path);
		my @all_int = read_all_line($int_path);

		my $sent = '';
		my @matched_idx = grep {
			$sent = $all_int[$_];
			grep { /\Q$sent/u } @all_abs;
		} 0..$#all_int;

		if (@matched_idx) {
			print "[$int_path] : @matched_idx\n";
			$num_done++;
		}

	}
}
print "$num_done input files matched\n";
