#!/usr/bin/perl -w
use strict;
use 5.010;
use utf8;
binmode(STDOUT, ":utf8");
#fgrep \\section *.tex

$#ARGV == 0 || die "Usage: ./section_classify [NAME OF DOC]\n";


# set list of section devider
my (@list_intro, @list_conclusion, @list_test);
@list_intro = qw/はじめに/;
@list_conclusion = qw/結論 おわりに 終わりに/;
@list_test = qw/実験/;
## sample: $re_* = "intro|introduction|introduce";
my ($re_intro, $re_conclusion, $re_test);
$re_intro = join '|', @list_intro;
$re_conclusion = join '|', @list_conclusion;
$re_test = join '|', @list_test;
### 関連研究
### 提案手法


# read file contents
my ($file_name, $file_lines);
$file_name = $ARGV[0];
open my $fh, '<:encoding(UTF-8)', $file_name || die "Can't open '$file_name': $!";
$file_lines = join '', <$fh>;



# classify section
## classify intro
if( $file_lines =~ /^\\section{$re_intro}/ump ) {
	print "found [${^MATCH}]\n";
}
## classify conclusion
if( $file_lines =~ /^\\section{(?:$re_conclusion)(?:\w)*}/ump ) {
	print "found [${^MATCH}]\n";
}
if( $file_lines =~ /^\\section{(?:$re_test)(?:\w)*}/ump ) {
	print "found [${^MATCH}]\n";
}
