#!/usr/bin/perl -w
use strict;

#parameter is V*
my ($total, $moved_cnt);
$total = 0;
$moved_cnt = 0;

my @list = <@ARGV>;
for my $file_name (@list) {
	$total++;

#	print "$file_name\n";
	my @num = split /-|\./, $file_name;

	if($num[1]%3 == 0) {
		system "mv $file_name ./test_data";
		$moved_cnt++;
	}
}
print "input file total: $total\n";
print "moved file total: $moved_cnt\n";
print "remain file: ".($total-$moved_cnt)."\n";

