#!/usr/bin/perl
use strict;
use utf8;

use lib qw(lib);
use Latex2Text ':all';

use open IO=> ':encoding(utf8)';
binmode STDIN, ':encoding(utf8)';
binmode STDOUT, ':encoding(utf8)';
binmode STDERR, ':encoding(utf8)';

for my $file (@ARGV) {
	open my $fh, '<', $file or die "can't open $file: $!";

	while (<$fh>) {
		my @sent = &LatexToSentencelist($_);
		print @sent;
	}
}
