#!/usr/bin/perl
use warnings;
use strict;

use v5.10; # using state
use open IO=> ':encoding(utf8)';
binmode STDIN, ':encoding(utf8)';
binmode STDOUT, ':encoding(utf8)';
binmode STDERR, ':encoding(utf8)';

my $path_ref = 'tet';
open my $fh, '<', $path_ref or die "Cannot open $path_ref: $!";
my $contents = join '', <$fh>;
close $fh;

print "matched!\n" if ($contents =~ /(?:\n){2,}/);
my @paragraphs = split /(?:\n){2,}/, $contents;
$" = "\n!!!!!!\n";
print "@paragraphs\n";
