#!/usr/bin/perl

use strict;
use utf8;

use open IO=> ':encoding(utf8)';
binmode STDIN, ':encoding(utf8)';
binmode STDOUT, ':encoding(utf8)';
binmode STDERR, ':encoding(utf8)';

use lib qw(lib);
use MeCab;
use Encode qw(decode);

print $MeCab::VERSION, "\n";

my $sentence = "太郎はこの本を二郎を見た女性に渡した。";

my $model = new MeCab::Model( '' );
my $c = $model->createTagger();
my $morpheme;
my $feature;
my $morphemes;
for (my $m = $c->parseToNode($sentence); $m; $m = $m->{next}) {
	$morpheme = $m->{surface};
	$morpheme = decode('utf8',$morpheme);
	$feature = $m->{feature};
	$feature = decode('utf8',$feature);
	my $pos = (split ',', $feature)[0];
	print $pos."\n";

	if ($pos eq '名詞') {
		print "seiko\n";
	}
	if ( ($morpheme =~ /^\w+$/u) && ($morpheme ne '') ) { # filetering special characters
#	push @{$morphemes->[$i]}, $morpheme;
	} else {
#		push @{$morphemes->[$i]}, '';
	}
}
