#!/usr/bin/perl
use utf8;
use lib qw(extlib/lib/perl5);
use Text::MeCab;
use Encode;
binmode (STDOUT, 'utf8');

my $str = "この文を形態素解析して下さい。、";
my $m = Text::MeCab->new();
my $n = $m->parse($str);
while ($n) {
	print "ok1\n"	if utf8::is_utf8($n->surface);
	print "ok2\n"	if utf8::is_utf8($n->feature);
	print "ok3\n"	if utf8::is_utf8($n->cost);
	my $surface = decode('utf8', $n->surface);
	my $feature = decode('utf8', $n->feature);
	my $cost = decode('utf8', $n->surface);
	print "re ok1\n"	if utf8::is_utf8($surface);
	print "re ok2\n"	if utf8::is_utf8($feature);
	print "re ok3\n"	if utf8::is_utf8($cost);
	printf "%s\t%s\t%d\n", $surface, $feature, $cost;
	$n = $n->next;
}

print "아이씨부랄 이거 왜이래\n";
