#!/usr/bin/perl
use warnings;
use strict;
use diagnostics;

#####
# 1. traverse zero sized rel_study file
# 2. seperate document to paragraph(devide by more than two return keys)
# 3. calc how many sentence each paragraph has
# 4. calc rel score of each paragraph
# 5. print the highest scored paragraph to the input zero sized rel_study file
#####


