#!/usr/bin/perl -w
use strict;

my $dir_path = './logs';
#opendir my $dh, $dir_path || die "Cannot open $dir_path: $!";
opendir my $dh, $dir_path or die "Cannot open $dir_path: $!";
my $temp=0;

for my $dir_ent (readdir $dh) {
	next if (-d $dir_ent) or $dir_ent eq '.' or $dir_ent eq '..';
	$temp++;
}
closedir $dh;
print $temp;

#full_log_section_classify
