#!/usr/bin/perl
use strict;
use warnings;


open my $fh_sys, '<', './test.output' or die "can't open test.output";
open my $fh_ans, '<', '../logs/intro_dev_test' or die "can't open test";

my $sys_1 = 0;
my $sys_2 = 0;
my $ans_0 = 0;
my $ans_1 = 0;
my $cnt =0;
my $sys_line;
my $ans_line;

for (0..807) {
	$sys_line = <$fh_sys>;
	$ans_line = <$fh_ans>;
	chomp $sys_line;
	my @fields = split / |\t/, $ans_line;
	$ans_line = $fields[0];

	if ($sys_line eq 1 ) {
		$sys_1++;
	} elsif ($sys_line eq 2 ) {
		$sys_2++;
	} else {
		print "???\n";
	}

	if ($ans_line eq 0 ) {
		$ans_0++;
	} elsif ($ans_line eq 1 ) {
		$ans_1++;
	} else {
		print "??????\n";
	}

	if (($sys_line eq 2) && ($ans_line eq 1)) {
		$cnt++;
	}
}

print "$sys_1, $sys_2\n";
print "$ans_0, $ans_1\n";
print "$cnt\n";

close $fh_sys;
close $fh_ans;
