#!/usr/bin/perl
use strict;
use warnings;

my $ret0;

my $cmd1 = "./remove_test_and_train_out";
my $cmd2 = "./libsvm_formatter.prl --training-mode --no-weight -v ../logs/intro_train -o training";
my $cmd3 = "./libsvm_formatter.prl --test-mode --no-weight -v ../logs/intro_dev_test -m training -o test";
#my $cmd4 = "svm-train -t 0 training.libsvm";
my $cmd4 = "svm-train -gamma=0.0078125 -cost=0.03125 -t 0 training.libsvm";
my $cmd5 = "svm-predict test.libsvm training.libsvm.model test.output";

print "\n\n";
print "===============================================\n";
my $ret1 = system "$cmd1";
print "[ $ret1, $cmd1 ]\n";
print "===============================================\n";
#$ret0 = system 'ls';
#print "-----------------------------------------------\n";

print "\n\n";
print "===============================================\n";
my $ret2 = system "$cmd2";
print "[ $ret2, $cmd2 ] \n";
print "===============================================\n";
#$ret0 = system 'ls';
#print "-----------------------------------------------\n";

print "\n\n";
print "===============================================\n";
my $ret3 = system "$cmd3";
print "[ $ret3, $cmd3 ] \n";
print "===============================================\n";
#$ret0 = system "ls";
#print "-----------------------------------------------\n";

print "\n\n";
print "===============================================\n";
my $ret4 = system "$cmd4";
print "[ $ret4, $cmd4 ] \n";
print "===============================================\n";
#$ret0 = system "ls";
#print "-----------------------------------------------\n";

print "\n\n";
print "===============================================\n";
my $ret5 = system "$cmd5";
print "[ $ret5, $cmd5 ] \n";
print "===============================================\n";
#$ret0 = system "ls";
#print "-----------------------------------------------\n";

